name: MCSports
version: Beta1 0.0.1
description: Aurean plugin for all sorts of sports for MCSports.
authors: [Mayoz, Taeir]
website: http://www.aurean.com/plugin_development/MCSports
main: com.aurean.ozonesports.OzoneSports

commands:
    game:
        description: placeholder
        aliases: osgame
    ozonesports:
        description: main OzoneSports Command
        aliases: sports
    referee:
        description: Referee command. Use /referee for more information
        aliases: osreferee

permissions:
    ozonesports.mod.game.allowjoin:
        description: Make a game joinable
        default: op
    ozonesports.game:
        description: Allows access to /game (help and info)
        default: true
    ozonesports.admin.reload:
        description: Allows to reload OzoneSports config
        default: op
        children:
            ozonesports.ozonesports: true
