name: MCSports
version: 0.0.1 (Beta1)
description: Aurean plugin for all sorts of sports for MCSports.
authors: [Mayoz, Taeir]
website: http://www.aurean.com/plugin_development/MCSports
main: com.aurean.mcsports.MCSports

commands:
    game:
        description: placeholder
        aliases: mcgame
    sports:
        description: main MCSports Command
        aliases: [ozonesports, mcsports]
    referee:
        description: Referee command. Use /referee for more information
        aliases: mcreferee

permissions:
    mcsports.mod.game.allowjoin:
        description: Make a game joinable
        default: op
    mcsports.game:
        description: Allows access to /game (help and info)
        default: true
    mcsports.admin.reload:
        description: Allows to reload MCSports config
        default: op
        children:
            ozonesports.ozonesports: true